[tool.pytest.ini_options]
minversion = 7.0
# durations=0 will display all tests execution time, sorted in ascending order starting from from the slowest one.
# -vv will also display tests with durration = 0.00s
# always add these arguments to pytest
addopts = [
    "--cache-clear",
    "--quiet",
    "--durations=0",
    "--cov=src/sagemaker_nemo_adaptor/",
    # uncomment this line to see a detailed HTML test coverage report instead of the usual summary table output to stdout.
    # "--cov-report=html",
    "tests/sagemaker_nemo_adaptor/",
]
# both of these entries are required so test coverage stats and imports within tests/ work correctly
pythonpath = ["src", "."]
testpaths = ["tests/sagemaker_nemo_adapter"]
norecursedirs = [".eggs", ".pytest_cache", "*.egg-info", ".git", "build", "requirements"]
filterwarnings = [
    "ignore::DeprecationWarning:lightning_fabric.*",
    "ignore::DeprecationWarning:pkg_resources.*",
    "ignore::DeprecationWarning:pytorch_lightning.*",
]
[tool.coverage.report]
fail_under = 50
