name: Pipeline Synthesis

env:
  # Replace with desired release branch (should be same for launcher and adapter)
  # e.g. 'release/v1.0.0'
  # Note that the launcher branch needs to be created first as a prerequisite
  BRANCH: 'main'
  PIPELINE_NAME_PREFIX: 'hp-recipes-pipeline'

on:
  create:
    branches:
      - 'main'
      # Note: Cannot use env variables for the trigger so make sure to add the env.BRANCH specified above
      # TODO: Find a better way to trigger without hard coding - possibly trigger for all "release/**" branches

permissions:
   id-token: write # This is required for requesting the JWT
   contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install git-remote-codecommit
        run: |
          python -m pip install --upgrade pip
          pip install git-remote-codecommit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.RUNNER_ROLE_ARN }}
          role-session-name: cdk-runner-session
          aws-region: us-west-2

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk
          pip install aws-cdk-lib

      - name: Pull from Integration Test Code Commit Replica
        run: |
          git clone codecommit::us-west-2://SagemakerTrainingLauncherIntegrationTests
          cd SagemakerTrainingLauncherIntegrationTests
          git checkout mainline
          git pull

      - name: Synthesize Pipeline
        run: |
          cd SagemakerTrainingLauncherIntegrationTests/cdk
          cdk deploy --require-approval never --region us-west-2 --context pipeline_name_prefix=${{ env.PIPELINE_NAME_PREFIX }} --context private_sagemaker_training_launcher_staging_branch_name=${{ env.BRANCH }} --context private_sagemaker_training_adapter_for_nemo_staging_branch_name=${{ env.BRANCH }}
