name: Pipeline Synthesis

env:
  # Note that the launcher branch needs to be created first as a prerequisite
  # Replace with desired launcher branch here, if not specified will use the same branch as the adaptor
  # LAUNCHER_BRANCH: 'main'
  PIPELINE_NAME_PREFIX: 'hp'

on:
  create:
    branches:
      - 'main'
      - 'release-*'

permissions:
   id-token: write # This is required for requesting the JWT
   contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python and pip
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install git-remote-codecommit
        run: |
          python -m pip install --upgrade pip
          pip install git-remote-codecommit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.RUNNER_ROLE_ARN }}
          role-session-name: cdk-runner-session
          aws-region: us-west-2

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk
          pip install aws-cdk-lib

      - name: Pull from Integration Test Code Commit Replica
        run: |
          git clone codecommit::us-west-2://SagemakerTrainingLauncherIntegrationTests
          cd SagemakerTrainingLauncherIntegrationTests
          git checkout mainline
          git pull

      - name: Synthesize Pipeline
        run: |
          cd SagemakerTrainingLauncherIntegrationTests/cdk
          if [ -n "${{ env.LAUNCHER_BRANCH }}" ]; then
            cdk deploy --require-approval never --region us-west-2 --context pipeline_name_prefix=${{ env.PIPELINE_NAME_PREFIX }} --context private_sagemaker_training_launcher_staging_branch_name=${{ env.LAUNCHER_BRANCH  }} --context private_sagemaker_training_adapter_for_nemo_staging_branch_name=${{ github.ref_name }}
          else
            cdk deploy --require-approval never --region us-west-2 --context pipeline_name_prefix=${{ env.PIPELINE_NAME_PREFIX }} --context private_sagemaker_training_launcher_staging_branch_name=${{ github.ref_name }} --context private_sagemaker_training_adapter_for_nemo_staging_branch_name=${{ github.ref_name }}
          fi
