name: Python Pre Commit Check CI After Commit

on:
  push:
    branches:
      - main # Triggers on direct pushes to the main branch

permissions:
   id-token: write # This is required for requesting the JWT
   contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Set python version to 3.10

      - name: Install pre-commit dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.RUNNER_ROLE_ARN }}
          role-session-name: precommit-check-push-session
          aws-region: us-west-2

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files
