name: Python Pre Commit Check CI

on:
  pull_request:
    branches:
      - main # Change to the branch we want to target for PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Set python version to 3.9

      - name: Install pre-commit dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files
