name: Python Unit Test CI

on:
  pull_request:
    branches:
      - main # Change to the branch we want to target for PRs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}

      - name: Review available disk space before cache cleanup
        run: |
          df -h

      - name: Clean docker cache
        run: |
          docker system prune -a --volumes -f
          docker image prune -a -f

      - name: Clean apt cache
        run: |
          sudo apt-get clean
          sudo apt-get autoremove

      - name : Clean hosted tool cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/go
          sudo rm -rf /opt/hostedtoolcache/microsoft

      - name : Clean android user cache
        run: |
          sudo rm -rf /usr/local/lib/android

      - name: Review available disk space after cache cleanup
        run: |
          df -h

      - name: Pull docker image
        run: docker pull ${{ secrets.ECR_REPO_URI }}:${{ secrets.ECR_IMAGE_TAG }}

      - name: Run unit tests
        run: |
          docker run --rm -v "${PWD}:/workspace" -w "/workspace" "${{ secrets.ECR_REPO_URI }}:${{ secrets.ECR_IMAGE_TAG }}" bash -c "pip install '.[all]' && pip install '.[test]' && TRAINING_JOB_ARN='SM_DUMMY_ARN' pytest"
